### ISSUE TITLE
User can input zip code to see available upcoming concerts in an area.

### ISSUE THREAD

**Issue by bbrown949** [bbrown949/ajax-project#1]
## ⚙️ Feature

Users will be able to input their zip code and get a live list of upcoming concerts in their area.

## 📐 Functionality

Create a responsive form that allows users to store available concerts with some notes about a specific concert.

## 🖼️ Wireframes

<img width="207" alt="Home_Mobile" src="https://user-images.githubusercontent.com/117103446/234110985-9541ac86-62e4-4870-8107-6bff71897590.png">
<img width="517" alt="Screenshot 2023-04-25 at 6 34 15 PM" src="https://user-images.githubusercontent.com/117103446/234443504-a2e03b68-febd-4e1f-bd8a-1af9b14dafe4.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create HTML for the home page so that it matches the figma example. Make sure to reference the included layout classes in code journal.
     - [x] create img element for home screen background image
     - [x] center the zip code input feature in center of page like in figma
     - [x] apply functionality to zip code feature.
     - [x] add event listener for keydown event that
          - [x] triggers geotagging API from Discovery API which will load shows onto the next page
 
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [ ] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
