### ISSUE TITLE
User can save concerts they are interested in

### ISSUE THREAD

**Issue by bbrown949** [bbrown949/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can hit a favorites icon/save button button on the api generated list of concerts for which events they are interested in going to.

## 🖼️ Wireframes

<img width="235" alt="Screenshot 2023-04-27 at 11 40 21 AM" src="https://user-images.githubusercontent.com/117103446/234961311-7bee2be6-14b8-498f-bbd8-37bdbb14fb81.png">
<img width="651" alt="Screenshot 2023-04-27 at 11 45 35 AM" src="https://user-images.githubusercontent.com/117103446/234962013-d14d710d-c72a-4d36-ab41-b42e7d54a8ba.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Add a favorite icon next to the concert text data returned from API
- [x] Add an submit event listener to the icon:
     - [x]  prevents the page from refreshing when the favorite icon is submitted.
     - [x] stores the form's input values in a new object.
     - [x] assigns an entryId property to the new object, taken from the nextEntryId property of the data model.
 increments the nextEntryId property of the data model so that if another entry is submitted later, it will receive a different entryId.
- [x]  adds the new object to the beginning of the data model's array of entries.
- [x] In data.js, add a 'beforeunload' event listener to the window object that serializes the data model as JSON and stores the JSON in localStorage.
- [x] At the bottom of data.js, include a conditional statement that:
 checks to see if there is a JSON data model stored in localStorage.
 if there is, parse it and assign it to the initial data variable so that the user can continue adding entries to the pre-existing data model.
- [x] turn home text in the navbar to an anchor link and add an event listener to it to switch back to the home view.
- [x] Test the app by submitting some new entries and then reloading the page to confirm that:
 the data model is being saved to localStorage before each page reload.
 each new journal entry object is receiving an incrementing entryId property.

 

- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
