### ISSUE TITLE
User can view saved concerts

### ISSUE THREAD

**Issue by bbrown949** [bbrown949/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to view favorited concerts on a new page where they will be able to add notes.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes
<img width="241" alt="Screenshot 2023-05-02 at 4 04 08 PM" src="https://user-images.githubusercontent.com/117103446/235803874-d51b71a4-c9a1-4128-9595-a4d1f563443d.png">
<img width="684" alt="Screenshot 2023-05-02 at 4 06 18 PM" src="https://user-images.githubusercontent.com/117103446/235804029-d144baf8-8ff2-4659-b760-9481dabf26c7.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add a new data view div for "my-concerts-page"
- [x] Add an empty unordered list to the div[data-view="my-concerts-page"] element in the HTML.
- [x] Define a function named renderMyConcerts with a single parameter named concerts. This parameter represents a single object for a single concert from the data.entries array. The function should generate and return a DOM tree for a single concert that matches the concerts that were imported from the API list.
- [x] when user clicks on the favorites icon:
     - [x] should Render a DOM tree for the newly submitted entry object using the renderMyConcerts function.
     - [x] prepends renderMyConcerts to the data view for my-concerts-page
- [x] add to the existing view swap function to incorporate view swapping to the my-concerts page
- [x] Uses the view swap to show the ”my-concerts” view.

- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
